swagger:
  application-url: http://localhost:${server.port}
  title: ${spring.application.name}
  version: 0.1.0
  application-description: Documentation about candidate service API endpoints  
  
spring:
  application:
    name: Candidate-Service-local
  profiles:
    active:
    - local
  servlet:
     multipart:
        max-file-size: 2MB
        max-request-size: 2MB
    
cron:
   expression:
      lockAtMost: 15m
      scheduledTaskAt: '@midnight'

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus","metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
      

---

spring:   
  config:
    activate:
      on-profile: local
      
  data:
    mongodb:
      database: candidatedb
      auto-index-creation: true
      uri: mongodb+srv://test:test@cluster0.0ftm8q2.mongodb.net/?retryWrites=true&w=majority #mongodb://127.0.0.1:27017
  
  rabbitmq:
    addresses: localhost:5672 
    listener:
      simple:
        default-requeue-rejected: false
        
logging:
  level[org.mongodb.driver]: WARN
  level[org.springframework.data.mongodb]: DEBUG
 
comms:
   api:
     x-api-key: 630eff62c08ba870e88cf7c0 
     amplify-service:
        base-uri: http://localhost:3001
        x-api-key: 630eff62c08ba870e88cf7c0

cors:
  allowedOrigins: '*'
  
management:
  server:
    port: ${server.port}
